Fix ci script to have correct exit code

diff --git a/environment/bin/kotlink_ci b/environment/bin/kotlink_ci
--- a/environment/bin/kotlink_ci
+++ b/environment/bin/kotlink_ci
@@ -1,5 +1,13 @@
 #!/usr/bin/env bash
 
+function destroy_environment() {
+	if [[ $? -gt 0 ]]; then
+	    echo -e "\033[31mERROR\033[m: CI pipeline has failed!"
+	fi
+	./environment/lib/env_down ci
+}
+
+trap destroy_environment EXIT
+
 ./environment/lib/env_up ci
 ./gradlew clean check jacocoTestReport
-./environment/lib/env_down ci
